export const debugControls = {
  meshOpacity: 0,
  depthStrength: 1.5,
  particleColor: "#202aff",
  peakStrength: 0.995,
  peakHoldLength: 0.5,
  softness: 0.75,
  sizeVariation: 0.12,
  cloudOpacity: 0.6,
  peakOpacity: 0.9,
  blendingMode: "normal",
  motionEnabled: true,
  motionAmount: 0.5,
  depthFade: 0.35,
  fluffiness: 0,
  subtleMotionStrength: 0.65,
  cloudSize: 1.2,
  spreadStrength: 2,
  noiseStrength: 0.4,
  noiseScale: 0.4,
  noiseEnabled: true,
};
